export const categories = [
    { id: 1, slug: "phones", name: "ТЕЛЕФОНЫ", src: "phone.png" },
    { id: 2, slug: "headphones", name: "НАУШНИКИ", src: "headphone.png" },
    { id: 3, slug: "tablet", name: "ПЛАНШЕТЫ", src: "tablet.png" },
    { id: 4, slug: "watch", name: "СМАРТ-ЧАСЫ", src: "watch.png" },
    { id: 5, slug: "laptop", name: "НОУТБУКИ", src: "laptop.png" },
    { id: 6, slug: "camera", name: "КАМЕРЫ", src: "camera.png" },
]

export const products = [
    {
        "id": 1,
        "name": "Apple iPhone 15 Pro Max eSIM 256 ГБ, «титановый бежевый»",
        "brand_id": 1,
        "price": "204 990 ₽",
        "photo": "/phones/iphone15.jpeg",
        "category_id": 1,
    },
    {
        "id": 2,
        "name": "Apple iPhone 15 Pro Max eSIM 256 ГБ, «титановый бежевый»",
        "brand_id": 1,
        "price": "204 990 ₽",
        "photo": "/phones/iphone15.jpeg",
        "category_id": 1,
    },
    {
        "id": 3,
        "name": "Apple iPhone 15 Pro Max eSIM 256 ГБ, «титановый бежевый»",
        "brand_id": 1,
        "price": "204 990 ₽",
        "photo": "/phones/iphone15.jpeg",
        "category_id": 1,
    },
    {
        "id": 4,
        "name": "Apple iPhone 15 Pro Max eSIM 256 ГБ, «титановый бежевый»",
        "brand_id": 1,
        "price": "204 990 ₽",
        "photo": "/phones/iphone15.jpeg",
        "category_id": 1,
    },
    {
        "id": 5,
        "name": "Наушники Apple AirPods 2, Bluetooth, вкладыши, белый ",
        "brand_id": 1,
        "price": "12 990 ₽",
        "photo": "/headphones/airpods.webp",
        "category_id": 2,
    },
    {
        "id": 6,
        "name": "Наушники Apple AirPods 2, Bluetooth, вкладыши, белый ",
        "brand_id": 1,
        "price": "12 990 ₽",
        "photo": "/headphones/airpods.webp",
        "category_id": 2,
    },
    {
        "id": 7,
        "name": "Наушники Apple AirPods 2, Bluetooth, вкладыши, белый ",
        "brand_id": 1,
        "price": "12 990 ₽",
        "photo": "/headphones/airpods.webp",
        "category_id": 2,
    },
]

export const brands = [
    { "id": 1, "name": "Apple", "slug": "apple", "logo": "apple.png" },
    { "id": 2, "name": "Samsung", "slug": "samsung", "logo": "samsung.png" },
    { "id": 3, "name": "Huawei", "slug": "huawei", "logo": "huawei.png" },
    { "id": 4, "name": "Xiaomi", "slug": "xiaomi", "logo": "xiaomi.png" },
]


export const variations = [
    { id: 1, category_id: 1, name: "Цвет" },
    { id: 2, category_id: 1, name: "Память" },
    { id: 3, category_id: 1, name: "Оперативная память" },
    { id: 4, category_id: 1, name: "Процессор" },
    { id: 5, category_id: 1, name: "Камера" },
    { id: 6, category_id: 1, name: "ОС" },
    { id: 7, category_id: 2, name: 'Диапазон частот' },
    { id: 8, category_id: 2, name: "Тип подключения" },
    { id: 9, category_id: 2, name: "Микрофон" },
    { id: 10, category_id: 2, name: "Время работы от одного заряда" },
    { id: 11, category_id: 1, name: "Дисплей" },
]

export const variation_options = [
    { id: 1, variation_id: 1, name: "черный цвет" },
    { id: 2, variation_id: 1, name: "белые цвет" },
    { id: 3, variation_id: 1, name: "красный цвет" },
    { id: 4, variation_id: 2, name: "128Гб" },
    { id: 5, variation_id: 2, name: "256Гб" },
    { id: 6, variation_id: 2, name: "512Гб" },
    { id: 7, variation_id: 3, name: "8Гб" },
    { id: 8, variation_id: 3, name: "12Гб" },
    { id: 9, variation_id: 4, name: "Snapdragon" },
    { id: 10, variation_id: 4, name: "Exynos" },
    { id: 11, variation_id: 5, name: "48/12/12Мп" },
    { id: 12, variation_id: 5, name: "12/12/12Мп" },
    { id: 13, variation_id: 6, name: "iOS" },
    { id: 14, variation_id: 6, name: "Android" },
    { id: 15, variation_id: 7, name: 'от 20 Гц до 15 кГц' },
    { id: 16, variation_id: 8, name: 'беспроводные bluetooth, True Wireless' },
    { id: 17, variation_id: 9, name: 'встроенный' },
    { id: 18, variation_id: 10, name: '5 ч' },
    { id: 19, variation_id: 10, name: '6 ч' },
    { id: 20, variation_id: 11, name: '6,1" (2556x1179), OLED'},
    { id: 21, variation_id: 4, name: 'A17 Pro'}
]

export const productsVariationOptions = [
    { id: 1, product_id: 1, variation_option_id: 20 },
    { id: 2, product_id: 1, variation_option_id: 21 },
    { id: 3, product_id: 1, variation_option_id: 4 },
    { id: 4, product_id: 1, variation_option_id: 11 },
    { id: 5, product_id: 2, variation_option_id: 20 },
    { id: 6, product_id: 2, variation_option_id: 21 },
    { id: 7, product_id: 2, variation_option_id: 4 },
    { id: 8, product_id: 2, variation_option_id: 11 },
    { id: 9, product_id: 3, variation_option_id: 20 },
    { id: 10, product_id: 3, variation_option_id: 21 },
    { id: 11, product_id: 3, variation_option_id: 4 },
    { id: 12, product_id: 3, variation_option_id: 11 },
    { id: 13, product_id: 4, variation_option_id: 20 },
    { id: 14, product_id: 4, variation_option_id: 21 },
    { id: 15, product_id: 4, variation_option_id: 4 },
    { id: 16, product_id: 4, variation_option_id: 11 },
    { id: 17, product_id: 5, variation_option_id: 15 },
    { id: 18, product_id: 5, variation_option_id: 16 },
    { id: 19, product_id: 5, variation_option_id: 17 },
    { id: 20, product_id: 5, variation_option_id: 18 },
    { id: 21, product_id: 6, variation_option_id: 15 },
    { id: 22, product_id: 6, variation_option_id: 16 },
    { id: 23, product_id: 6, variation_option_id: 17 },
    { id: 24, product_id: 6, variation_option_id: 18 },
    { id: 25, product_id: 7, variation_option_id: 15 },
    { id: 26, product_id: 7, variation_option_id: 16 },
    { id: 27, product_id: 7, variation_option_id: 17 },
    { id: 28, product_id: 7, variation_option_id: 18 },
]