export const categories = [
    { id: 1, slug: "phones", name: "Телефоны", src: "phone.png" },
    { id: 2, slug: "headphones", name: "Наушники", src: "headphone.png" },
    { id: 3, slug: "tablet", name: "Планшеты", src: "tablet.png" },
    { id: 4, slug: "watch", name: "Смарт-часы", src: "watch.png" },
    { id: 5, slug: "laptop", name: "Ноутбуки", src: "laptop.png" },
    { id: 6, slug: "camera", name: "Камеры", src: "camera.png" },
]

export const products = [
    {
        "id": 50,
        "SKU": '201S23',
        "model": "Samsung_Galaxy_S23",
        "name": '6.1" Samsung Galaxy S23 128 ГБ черный',
        "brand_id": 2,
        "price": "74 999 ₽",
        "photo": "/phones/galaxys23.webp",
        "category_id": 1,
        "color": "black",
        "storage": 128,       
        "specifications": [
            { name: "Дисплей", value: '6,1" (2556x1179), OLED' },
            { name: "Процессор", value: 'Qualcomm Snapdragon 8 Gen2' },
            { name: "Память", value: '128 Гб' },
            { name: "Камеры", value: '50/12/10 Мп' },
            { name: "Система", value: 'Android 13' },
            { name: "Цвет", value: 'черный' },
            { name: "Оперативная память", value: '8Гб' },
        ],
    },
    {
        "id": 51,
        "SKU": '201S23',
        "model": "Samsung_Galaxy_S23",
        "name": '6.1" Samsung Galaxy S23 128 ГБ белый',
        "brand_id": 2,
        "price": "74 999 ₽",
        "photo": "/phones/galaxys23.webp",
        "category_id": 1,
        "color": "white",
        "storage": 128,       
        "specifications": [
            { name: "Дисплей", value: '6,1" (2556x1179), OLED' },
            { name: "Процессор", value: 'Qualcomm Snapdragon 8 Gen2' },
            { name: "Память", value: '128 Гб' },
            { name: "Камеры", value: '50/12/10 Мп' },
            { name: "Система", value: 'Android 13' },
            { name: "Цвет", value: 'белый' },
            { name: "Оперативная память", value: '8Гб' },
        ],
    },
    {
        "id": 52,
        "SKU": '201S23',
        "model": "Samsung_Galaxy_S23",

        "name": '6.1" Samsung Galaxy S23 256 ГБ синий',
        "brand_id": 2,
        "price": "74 999 ₽",
        "photo": "/phones/galaxys23.webp",
        "category_id": 1,
        "color": "blue",
        "storage": 256,       
        "specifications": [
            { name: "Дисплей", value: '6,1" (2556x1179), OLED' },
            { name: "Процессор", value: 'Qualcomm Snapdragon 8 Gen2' },
            { name: "Память", value: '256 Гб' },
            { name: "Камеры", value: '50/12/10 Мп' },
            { name: "Система", value: 'Android 13' },
            { name: "Цвет", value: 'синий' },
            { name: "Оперативная память", value: '8Гб' },
        ],
    },
    {
        "id": 53,
        "SKU": '201S23',
        "model": "Samsung_Galaxy_S23",

        "name": '6.1" Samsung Galaxy S23 256 ГБ белый',
        "brand_id": 2,
        "price": "74 999 ₽",
        "photo": "/phones/galaxys23.webp",
        "category_id": 1,
        "color": "white",
        "storage": 256,       
        "specifications": [
            { name: "Дисплей", value: '6,1" (2556x1179), OLED' },
            { name: "Процессор", value: 'Qualcomm Snapdragon 8 Gen2' },
            { name: "Память", value: '256 Гб' },
            { name: "Камеры", value: '50/12/10 Мп' },
            { name: "Система", value: 'Android 13' },
            { name: "Цвет", value: 'белый' },
            { name: "Оперативная память", value: '8Гб' },
        ],
    },
    {
        "id": 54,
        "SKU": '201S23',
        "model": "Samsung_Galaxy_S23",
        "name": '6.1" Samsung Galaxy S23 512 ГБ белый',
        "brand_id": 2,
        "price": "74 999 ₽",
        "photo": "/phones/galaxys23.webp",
        "category_id": 1,
        "color": "white",
        "storage": 512,
        "specifications": [
            { name: "Дисплей", value: '6,1" (2556x1179), OLED' },
            { name: "Процессор", value: 'Qualcomm Snapdragon 8 Gen2' },
            { name: "Память", value: '512 Гб' },
            { name: "Камеры", value: '50/12/10 Мп' },
            { name: "Система", value: 'Android 13' },
            { name: "Цвет", value: 'белый' },
            { name: "Оперативная память", value: '8Гб' },
        ],
    },
    {
        "id": 55,
        "SKU": '201S23',
        "model": "Samsung_Galaxy_S23",
        "name": '6.1" Samsung Galaxy S23 512 ГБ черный',
        "brand_id": 2,
        "price": "74 999 ₽",
        "photo": "/phones/galaxys23.webp",
        "category_id": 1,
        "color": "black",
        "storage": 512,
        "specifications": [
            { name: "Дисплей", value: '6,1" (2556x1179), OLED' },
            { name: "Процессор", value: 'Qualcomm Snapdragon 8 Gen2' },
            { name: "Память", value: '512 Гб' },
            { name: "Камеры", value: '50/12/10 Мп' },
            { name: "Система", value: 'Android 13' },
            { name: "Цвет", value: 'черный' },
            { name: "Оперативная память", value: '8Гб' },
        ],
    },
]

export const brands = [
    { "id": 1, "name": "Apple", "slug": "apple", "logo": "apple.png" },
    { "id": 2, "name": "Samsung", "slug": "samsung", "logo": "samsung.png" },
    { "id": 3, "name": "Huawei", "slug": "huawei", "logo": "huawei.png" },
    { "id": 4, "name": "Xiaomi", "slug": "xiaomi", "logo": "xiaomi.png" },
]


export const variations = [
    { id: 1, category_id: 1, name: "Цвет" },
    { id: 2, category_id: 1, name: "Память" },
    { id: 3, category_id: 1, name: "Оперативная память" },
    { id: 4, category_id: 1, name: "Процессор" },
    { id: 5, category_id: 1, name: "Камера" },
    { id: 7, category_id: 2, name: 'Диапазон частот' },
    { id: 8, category_id: 2, name: "Тип соединения" },
    { id: 9, category_id: 2, name: "Микрофон" },
    { id: 10, category_id: 2, name: "Время работы от одного заряда" },
]

export const variation_options = [
    { id: 1, variation_id: 1, name: "черный" },
    { id: 2, variation_id: 1, name: "белый" },
    { id: 3, variation_id: 1, name: "красный" },
    { id: 4, variation_id: 2, name: "128Гб" },
    { id: 5, variation_id: 2, name: "256Гб" },
    { id: 6, variation_id: 2, name: "512Гб" },
    { id: 7, variation_id: 3, name: "8Гб" },
    { id: 8, variation_id: 3, name: "12Гб" },
    { id: 9, variation_id: 4, name: "Snapdragon" },
    { id: 10, variation_id: 4, name: "Exynos" },
    { id: 11, variation_id: 5, name: "48/12/12 Мп" },
    { id: 12, variation_id: 4, name: "A17 Pro" },
    { id: 15, variation_id: 7, name: 'от 20 Гц до 15 кГц' },
    { id: 16, variation_id: 8, name: 'беспроводные bluetooth, True Wireless' },
    { id: 17, variation_id: 9, name: 'встроенный' },
    { id: 18, variation_id: 10, name: '5 ч' },
    { id: 19, variation_id: 10, name: '6 ч' },
    { id: 20, variation_id: 1, name: "титановый бежевый" },
    { id: 21, variation_id: 1, name: "титановый синий" },
    { id: 22, variation_id: 1, name: "синий" },

]
